<template>
 <div id="app">
    <div class="page">
      <div class="bg-white">
        <h1 class="title">Таблица ключей китайских иероглифов</h1>
        <div class="grid">
          <CardComp v-for="(card, index) in cards" :key="card.id" :title="card.title" :index="index"></CardComp>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import CardComp from '../components/CardComp.vue';
export default {
    components: {
        CardComp,
    },
     data() {
    return {
      newCardText: '',
      cards: [
        {
          id: 1,
          title: ''
        },
        {
          id: 2,
          title: ''
        },
        {
          id: 3,
          title: ''
        },
        {
          id: 4,
          title: ''
        }, {
          id: 5,
          title: ''
        }, {
          id: 6,
          title: ''
        }, {
          id: 7,
          title: ''
        }, {
          id: 8,
          title: ''
        }, {
          id: 9,
          title: ''
        }, {
          id: 10,
          title: ''
        }, {
          id: 11,
          title: ''
        }, {
          id: 12,
          title: ''
        }, {
          id: 13,
          title: ''
        }, {
          id: 14,
          title: ''
        }, {
          id: 15,
          title: ''
        }, {
          id: 16,
          title: ''
        }, {
          id: 17,
          title: ''
        }, {
          id: 18,
          title: ''
        }, {
          id: 19,
          title: ''
        }, {
          id: 20,
          title: ''
        }, {
          id: 21,
          title: ''
        }, {
          id: 22,
          title: ''
        }, {
          id: 23,
          title: ''
        }, {
          id: 24,
          title: ''
        }, {
          id: 25,
          title: ''
        }, {
          id: 26,
          title: ''
        }, {
          id: 27,
          title: ''
        }, {
          id: 28,
          title: ''
        }, {
          id: 29,
          title: ''
        }, {
          id: 30,
          title: ''
        }, {
          id: 31,
          title: ''
        }, {
          id: 32,
          title: ''
        }, {
          id: 33,
          title: ''
        }, {
          id: 34,
          title: ''
        }, {
          id: 35,
          title: ''
        }, {
          id: 36,
          title: ''
        }, {
          id: 37,
          title: ''
        }, {
          id: 38,
          title: ''
        }, {
          id: 39,
          title: ''
        }, {
          id: 40,
          title: ''
        }, {
          id: 41,
          title: ''
        }, {
          id: 42,
          title: ''
        }, {
          id: 43,
          title: ''
        }, {
          id: 44,
          title: ''
        }, {
          id: 45,
          title: ''
        }, {
          id: 46,
          title: ''
        }, {
          id: 47,
          title: ''
        }, {
          id: 48,
          title: ''
        }, {
          id: 49,
          title: ''
        }, {
          id: 50,
          title: ''
        },
        {
          id: 51,
          title: ''
        },
        {
          id: 52,
          title: ''
        },
        {
          id: 53,
          title: ''
        },
        {
          id: 54,
          title: ''
        }, {
          id: 55,
          title: ''
        }, {
          id: 56,
          title: ''
        }, {
          id: 57,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        }, {
          id: 51,
          title: ''
        },

      ]
    }
  }
}
</script>

<style scoped>
</style>